(() => {
'use strict';
const $ = (sel, ctx=document) => ctx.querySelector(sel);
const $$ = (sel, ctx=document) => Array.from(ctx.querySelectorAll(sel));
const norm = s => String(s||'').toLocaleLowerCase('ru').replaceAll('ё','е').replace(/\s+/g,' ').trim();
const asset = which => $('#'+which+'Asset')?.getAttribute('src') || ('assets/'+which+'.webp');
const text = (tag,content,cl) => {const e=document.createElement(tag);e.textContent=content;if(cl)e.className=cl;return e;};
const icons = {epi:'◈',endo:'◇',local:'✳',angio:'⬡',systemic:'◎'};
const endos=[
{id:'epi',short:'Эпителиальный',name:'Эпителиальное повреждение',tint:'#e7f2ff',tone:'#176acb',target:'Альвеолярные эпителиальные клетки',mechanism:'Нарушается транспорт воды и ионов через эпителий, снижается выведение жидкости из альвеол.',examples:'Калицивирус кошек, грипп собак, повреждение при ИВЛ, нарушения сурфактанта.',dad:'Некроз пневмоцитов, альвеолярный отёк; возможны изменения эпителия дыхательных путей.',desc:'Первичное воздействие на пневмоциты I и II типов нарушает эпителиальный барьер и клиренс жидкости. Повреждённые клетки могут привлекать лейкоциты и участвовать в образовании гиалиновых мембран.'},
{id:'endo',short:'Эндотелиальный',name:'Эндотелиальное повреждение',tint:'#e5f8f5',tone:'#068b7e',target:'Сосудистый эндотелий лёгких',mechanism:'Усиление сосудистой проницаемости, адгезии клеток и прокоагулянтных реакций.',examples:'Уремический пневмонит.',dad:'Реактивные изменения эндотелия, отёк интерстиция и альвеол, секвестрация нейтрофилов, тромбоз.',desc:'Повреждение сосудистого барьера сопровождается нарушением регуляции воспаления и водного обмена; активированные эндотелиоциты взаимодействуют с нейтрофилами и тромбоцитами.'},
{id:'local',short:'Местное воспаление',name:'Местная воспалительная реакция',tint:'#fff0e7',tone:'#c86f2f',target:'Первичный воспалительный очаг в лёгком',mechanism:'Воспаление распространяется из воздухоносных путей и затрагивает несколько тканевых компартментов.',examples:'Распространение бактериальной бронхопневмонии; воспалительный компонент аспирационной пневмонии.',dad:'Неспецифическое повреждение нескольких клеточных популяций и анатомических отделов.',desc:'Местное воспаление может усиливать повреждение эпителия и интерстиция. Нейтрофильные экссудаты высвобождают активные формы кислорода, взаимодействуют с макрофагами и нарушают барьерные функции.'},
{id:'angio',short:'Ангиопатия',name:'Ангиопатия',tint:'#f0ebff',tone:'#7657b9',target:'Микроциркуляторное русло',mechanism:'Вазоконстрикция и протромботический сосудистый фенотип могут приводить к микротромбозу.',examples:'В таблице 3 подходящих подтверждённых примеров у кошек и собак не приведено.',dad:'Микротромбы, фибриноидный некроз сосудов.',desc:'Выделена по сосудистым нарушениям, особенно в исследованиях COVID-19 у людей. Авторы предполагают, что при vetARDS этот эндотип может быть подгруппой эндотелиального.'},
{id:'systemic',short:'Системное воспаление',name:'Системная воспалительная реакция',tint:'#fff0f0',tone:'#c45165',target:'Внелёгочный воспалительный процесс и системные сосудистые реакции',mechanism:'Медиаторы системного воспаления вызывают сосудистую дисрегуляцию и повреждение лёгких.',examples:'Сепсис, панкреатит; бронхопневмония при развитии сепсиса.',dad:'Отёк лёгких, секвестрация нейтрофилов, отсутствие вовлечения воздухоносных путей в типичном варианте.',desc:'При сепсисе или ССВР медиаторы воспаления и активация эндотелия могут вовлекать лёгкие. Рассматриваются оксидативный стресс, коагуляция, комплемент, иммунная дисрегуляция и микрососудистые нарушения.'}
];
const stages=[
{period:'0–7 суток',name:'Экссудативная',subtitle:'Острая стадия',body:'Ранняя реакция на повреждение альвеолярных перегородок. Если прошло менее 24 часов, гистологические изменения могут быть минимальными.',signs:['Гиалиновые мембраны вдоль альвеолярных перегородок','Интерстициальный и интраальвеолярный отёк ± кровоизлияния','Возможны нейтрофильные инфильтраты и тромбоз'],pos:'0% 0%'},
{period:'с 3–7 суток',name:'Пролиферативная',subtitle:'Организационная стадия',body:'Начинается репарация: гиперплазия и гипертрофия пневмоцитов II типа с вовлечением интерстициальных клеток.',signs:['Гиперплазия пневмоцитов II типа, выраженная к 7-м суткам','Пролиферация фибробластов и миофибробластов','Мононуклеарная инфильтрация интерстиция'],pos:'100% 66.6667%'},
{period:'≈14-е сутки',name:'Фиброзирующая',subtitle:'Возможная хроническая стадия',body:'При более выраженном повреждении развивается отложение коллагена, фиброз альвеолярных перегородок и изменение структуры лёгкого.',signs:['Выраженный интерстициальный и/или интраальвеолярный фиброз','Персистенция пневмоцитов II типа','Возможны метаплазия и ремоделирование сосудов'],pos:'0% 100%'}
];
const histology=[
['A','Гиалиновые мембраны','В альвеолярных пространствах у собаки с лёгочной гипертензией вследствие врождённого порока сердца.'],
['B','Отёк альвеолярных перегородок','На фоне тромбоза лёгочных сосудов при амилоидозе почек у собаки.'],
['C','Нейтрофильная инфильтрация','Острая интерстициальная пневмония у кошки, предположительно связанная с инфекционным перитонитом.'],
['D','Тромб в лёгочном сосуде','Собака с сопутствующей лимфомой кишечника.'],
['E','Пролиферация фибробластов','Интерстиций и стенка воздухоносного пути; ингалированное инородное тело у собаки.'],
['F','Гиперплазия пневмоцитов II типа','После вдыхания инородного тела у собаки.'],
['G','Хронический интерстициальный фиброз','У собаки с хронической лёгочной гипертензией.'],
['H','Ремоделирование сосудов','На фоне хронической лёгочной гипертензии у собаки.']
];
const cases=[
{id:'influenza',name:'Вирус гриппа A',who:['dog','cat'],emoji:'🦠',label:'ВИРУСЫ',type:['epi'],excerpt:'У собак высокопатогенный A(H5N1) вызывал признаки, совместимые с ОРДС, и острую нейтрофильную интерстициальную пневмонию; у кошек описано подтверждённое ДАП с признаками ОРДС.',anchor:'Цитолитические респираторные вирусы'},
{id:'calici',name:'Калицивирус кошек',who:['cat'],emoji:'🐈',label:'ВИРУСЫ',type:['epi'],excerpt:'Описана тяжёлая острая пневмония с некрозом пневмоцитов. Авторы предполагают развитие ОРДС; гиалиновые мембраны не были описаны, поэтому ДАП не подтверждено.',anchor:'Цитолитические респираторные вирусы'},
{id:'ventilation',name:'ИВЛ и нарушения сурфактанта',who:['dog'],emoji:'🫁',label:'МЕХАНИКА',type:['epi'],excerpt:'Повреждение пневмоцитов при чрезмерном растяжении и повторном спадении/раскрытии альвеол. В семье эрдельтерьеров описано подтверждённое ДАП при врождённом нарушении сурфактанта.',anchor:'Повреждение лёгких, вызванное ИВЛ'},
{id:'toxins',name:'Токсичные газы и дым',who:['dog','cat'],emoji:'🌫️',label:'ИНГАЛЯЦИЯ',type:['epi'],excerpt:'Авторы рассматривают кислород (100%), диоксид азота, хлор, дым, а также паракват у собак как причины повреждения эпителия с риском ОРДС.',anchor:'Ингаляционные токсичные газы'},
{id:'aspiration',name:'Аспирационная пневмония',who:['dog','cat'],emoji:'💧',label:'АСПИРАЦИЯ',type:['epi','local'],excerpt:'Аспирация кислого желудочного содержимого повреждает эпителий; последующая нейтрофильная реакция может усиливать воспаление. В исследовании 46 собак аспирационная пневмония составляла 42% факторов риска vetARDS/ДАП.',anchor:'Аспирационная пневмония'},
{id:'uremia',name:'Уремическое повреждение',who:['dog','cat'],emoji:'🩸',label:'МЕТАБОЛИЗМ',type:['endo'],excerpt:'При уремии описаны альвеолярный отёк и минерализация перегородок. В приведённых исследованиях собак и кошек гиалиновые мембраны не сообщались; клинический ОРДС ретроспективно не подтверждён.',anchor:'Уремия — эндотелиальный'},
{id:'pneumonia',name:'Бактериальная бронхопневмония',who:['dog','cat'],emoji:'🧫',label:'ИНФЕКЦИЯ',type:['local','systemic'],excerpt:'Местное воспаление может повреждать интерстиций. При развитии сепсиса возможен эндотип системной воспалительной реакции. Авторы указывают на недостаток проспективных контролируемых исследований.',anchor:'Бактериальная бронхопневмония'},
{id:'pancreatitis',name:'Панкреатит',who:['dog','cat'],emoji:'🧬',label:'СИСТЕМНОЕ',type:['systemic'],excerpt:'У собак с острым панкреатитом в одной серии 33 из 109 имели респираторные признаки, в том числе 3 случая vetARDS; у кошек нарушения дыхания также могут быть связаны с ОПЛ/ОРДС.',anchor:'Панкреатит — эндотип'}
];
const bookmarks={concept:{title:'ДАП и ОРДС: разграничение',view:'overview'},timeline:{title:'Гистологические стадии ДАП',view:'stages'},endotype:{title:'Пять эндотипов ОРДС',view:'endotypes'},subtypes:{title:'Субфенотипы P1 и P2',view:'endotypes'}};
const bookmarkKey='vetscope_ards_bookmarks_v1';let saved=new Set();try{saved=new Set(JSON.parse(localStorage.getItem(bookmarkKey)||'[]'));}catch(e){}
let currentView='overview',caseFilter='all',stageIndex=0,endoId='epi',toastTimeout;
const toast=(message)=>{const t=$('#toast');t.textContent=message;t.classList.add('open');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>t.classList.remove('open'),2300)};
function view(v, chapter){
 if(!$('.section-view[data-view="'+v+'"]'))v='overview';currentView=v;
 $$('.section-view').forEach(e=>e.classList.toggle('active',e.dataset.view===v));
 $$('[data-go]').forEach(e=>e.classList.toggle('active',e.dataset.go===v));
 try{history.replaceState(null,'','#'+v);}catch(e){}
 window.scrollTo({top:0,behavior:'instant'});updateProgress();
 if(v==='saved')renderSaved();
 if(v==='reader'&&chapter){setTimeout(()=>openReaderBy(chapter),60)}
}
function openReaderBy(query){
 const q=norm(query);const chapters=$$('#readerChapters .chapter');let target=chapters.find(e=>norm(e.dataset.chapter).includes(q));let sub=null;
 if(!target){for(const c of chapters){sub=$$('h2,h3,h4',c).find(h=>norm(h.textContent).includes(q));if(sub){target=c;break;}}}
 if(target){target.open=true;const dest=sub||target;setTimeout(()=>dest.scrollIntoView({behavior:'smooth',block:'start'}),60)}
}
function markBookmark(id){if(saved.has(id))saved.delete(id);else saved.add(id);try{localStorage.setItem(bookmarkKey,JSON.stringify([...saved]));}catch(e){}syncBookmarks();toast(saved.has(id)?'Добавлено в закладки':'Удалено из закладок')}
function syncBookmarks(){const count=$('#savedCount');count.textContent=saved.size?'· '+saved.size:'';$$('[data-bookmark]').forEach(b=>{const on=saved.has(b.dataset.bookmark);b.classList.toggle('saved',on);const sp=$('span',b);if(sp)sp.textContent=on?'Сохранено':'Сохранить';});if(currentView==='saved')renderSaved();}
function renderSaved(){const slot=$('#savedItems');slot.textContent='';if(!saved.size){slot.append(text('p','Пока нет закладок. Откройте обзор и нажмите «Сохранить» возле интересующей карточки.','subline'));return;}for(const key of saved){const b=bookmarks[key];if(!b)continue;const wrapper=text('div','','side-card');wrapper.style.display='flex';wrapper.style.alignItems='center';wrapper.style.justifyContent='space-between';wrapper.style.gap='12px';const btn=text('button',b.title,'btn');btn.dataset.go=b.view;const rm=text('button','Убрать','filter');rm.addEventListener('click',()=>markBookmark(key));wrapper.append(btn,rm);slot.append(wrapper)}}
function renderStages(){const bar=$('#stagesBar');stages.forEach((s,i)=>{const b=text('button','', 'stage-btn');b.type='button';b.dataset.stage=String(i);b.innerHTML='<div class="stage-day"></div><div class="stage-label"></div>';$('.stage-day',b).textContent=s.period;$('.stage-label',b).textContent=s.name;$('.stage-label',b).append(text('small',s.subtitle));b.addEventListener('click',()=>selectStage(i));bar.append(b)});selectStage(0);}
function selectStage(i){stageIndex=i;const s=stages[i];$$('[data-stage]').forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-pressed',String(j===i))});$('#stageName').textContent=s.name+' стадия';$('#stageDesc').textContent=s.body;$('#stageSigns').replaceChildren(...s.signs.map(v=>text('li',v)));$('#stageThumb').style.backgroundPosition=s.pos}
function renderHistology(){const parent=$('#histologyTiles');histology.forEach(([letter,name,desc],i)=>{const card=text('button','','');card.type='button';card.style='display:flex;gap:11px;align-items:center;min-width:0;border:1px solid #e1e8f2;border-radius:11px;padding:7px;background:white;text-align:left';const im=document.createElement('div');im.style=`width:106px;aspect-ratio:1.65;flex:none;border-radius:7px;background-image:url('${asset('figure1')}');background-size:200% 400%;background-position:${i%2*100}% ${Math.floor(i/2)/3*100}%;`;const info=document.createElement('div');const h=text('div',`${letter} · ${name}`);h.style='font-size:12px;font-weight:800;color:#2b4058';const d=text('div',desc);d.style='font-size:11px;color:#72839a;line-height:1.4;margin-top:3px';info.append(h,d);card.append(im,info);card.addEventListener('click',()=>openImage('figure1'));parent.append(card)})}
function renderEndos(){const buttons=$('#endoButtons'),mini=$('#miniEndos');endos.forEach(e=>{const b=text('button','','endo-option');b.style=`--tint:${e.tint};--tone:${e.tone}`;b.dataset.endo=e.id;b.innerHTML='<span class="endo-icon"></span><span class="endo-caption"></span>';$('.endo-icon',b).textContent=icons[e.id];$('.endo-caption',b).textContent=e.short;b.addEventListener('click',()=>selectEndo(e.id));buttons.append(b);const tag=text('button',e.short,'filter');tag.addEventListener('click',()=>{view('endotypes');selectEndo(e.id)});mini.append(tag)});selectEndo('epi')}
function selectEndo(id){endoId=id;const e=endos.find(x=>x.id===id);$$('.endo-option').forEach(b=>{b.classList.toggle('active',b.dataset.endo===id);b.setAttribute('aria-pressed',String(b.dataset.endo===id))});const detail=$('#endoDetail');detail.replaceChildren();const title=text('h3',e.name);const body=text('div',e.desc,'endo-text');const fields=text('div','','endo-fields');[['Основная мишень',e.target],['Первичный механизм',e.mechanism],['Примеры из статьи',e.examples],['Возможные признаки при ДАП',e.dad]].forEach(([k,v])=>{const f=text('div','','endo-field');f.append(text('label',k),text('div',v));fields.append(f)});detail.append(title,body,fields);const bottom=text('div','Механизмы представляют исследовательскую классификацию; отдельные случаи могут сочетать несколько эндотипов.','endo-remark');detail.append(bottom)}
function renderCases(){const grid=$('#caseGrid');grid.replaceChildren();const filtered=cases.filter(c=>caseFilter==='all'||c.who.includes(caseFilter));$('#caseEmpty').hidden=filtered.length!==0;filtered.forEach(c=>{const card=text('div','','case-card');const art=text('div','','case-art');art.append(text('div',c.label,'small-label'),text('div',c.emoji,'emoji'));const body=text('div','','case-content');body.append(text('h3',c.name),text('p',c.excerpt));const tags=text('div','','case-tags');c.type.forEach(id=>tags.append(text('span',endos.find(e=>e.id===id).short)));body.append(tags);const foot=text('div','','case-footer');foot.append(text('span',c.who.length===2?'Собаки и кошки':c.who[0]==='dog'?'Собаки':'Кошки'));const link=text('button','Читать в статье →');link.addEventListener('click',()=>view('reader',c.anchor));foot.append(link);card.append(art,body,foot);grid.append(card)})}
function openImage(which){const cap={figure1:'Рисунок 1. Гистологические признаки ДАП у собак и кошек (H&E, панели A–H). Полная подпись в разделе «Полный перевод».',figure2:'Рисунок 2. Механизмы эпителиального, эндотелиального, местного и системного воспалительных эндотипов и ангиопатии (Wong & Boyle, 2026).'};$('#lightboxImg').src=asset(which);$('#lightboxCaption').textContent=cap[which];$('#lightbox').classList.add('open');document.body.style.overflow='hidden';$('#lightboxClose').focus()}
function closeImage(){$('#lightbox').classList.remove('open');$('#lightboxImg').src='';document.body.style.overflow=''}
function openSearch(query=''){$('#searchOverlay').classList.add('open');$('#searchInput').value=query;renderSearch();setTimeout(()=>$('#searchInput').focus(),50)}
function closeSearch(){$('#searchOverlay').classList.remove('open')}
function renderSearch(){const q=norm($('#searchInput').value);const el=$('#searchResults');el.replaceChildren();if(!q){el.append(text('div','Поиск по русскому переводу, заголовкам разделов и библиографии. Введите термин или фамилию автора.','side-mini'));return;}const hits=(window.ARTICLE_SEARCH||[]).map((item)=>{const hay=norm(item.text);const title=norm(item.title);const offset=hay.indexOf(q);return {...item,rank:title.includes(q)?100:offset>=0?10:0,offset}}).filter(i=>i.rank).sort((a,b)=>b.rank-a.rank).slice(0,14);if(!hits.length){el.append(text('div','Совпадений не найдено. Попробуйте другую форму слова.','subline'));return;}hits.forEach(hit=>{const btn=text('button','','search-result');const snippet=hit.text.replace(/\s+/g,' ').slice(Math.max(0,hit.offset-65),Math.max(0,hit.offset-65)+215);btn.append(text('strong',hit.title),text('span',snippet));btn.addEventListener('click',()=>{closeSearch();view('reader',hit.heading||hit.title)});el.append(btn)});el.append(text('p',`Показано ${hits.length} наиболее релевантных разделов.`, 'side-mini'))}
function updateProgress(){const max=Math.max(1,document.documentElement.scrollHeight-window.innerHeight),pct=Math.min(100,Math.max(0,Math.round(window.scrollY/max*100)));$('#progressText').textContent=pct+'%';$('#progressFill').style.width=pct+'%'}
function share(){const url=location.href.split('#')[0]+'#'+currentView;const success=()=>toast('Ссылка на раздел скопирована');if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(url).then(success,()=>fallbackCopy(url));}else fallbackCopy(url)}
function fallbackCopy(url){const el=document.createElement('textarea');el.value=url;el.style.position='fixed';el.style.opacity='0';document.body.append(el);el.select();let success=false;try{success=document.execCommand('copy')}catch(e){}el.remove();toast(success?'Ссылка на раздел скопирована':'Адрес раздела: '+url)}
function activateSource(action){if(action==='share')share();if(action==='print')window.print();if(action==='open-source')window.open('https://doi.org/10.1177/10406387261418009','_blank','noopener,noreferrer');if(action==='download-ru')window.open('assets/article_ru.pdf','_blank','noopener')}
// Ссылки [12, 34] в переводе направляют на нумерованную библиографию.
function linkCitations(){const reader=$('#readerChapters');const w=document.createTreeWalker(reader,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=w.nextNode()){if(n.parentElement.closest('a,code,pre,.reference'))continue;if(/\[\d+(?:,\s*\d+)*\]/.test(n.nodeValue))nodes.push(n)}nodes.forEach(node=>{const pieces=node.nodeValue.split(/(\[\d+(?:,\s*\d+)*\])/g);const frag=document.createDocumentFragment();pieces.forEach(piece=>{if(/^\[\d+(?:,\s*\d+)*\]$/.test(piece)){const nums=piece.slice(1,-1).split(/,\s*/);const span=document.createElement('span');span.append('[');nums.forEach((r,i)=>{if(i)span.append(', ');const a=text('a',r,'inline-ref');a.href='#reference-'+r;a.addEventListener('click',ev=>{ev.preventDefault();view('reader');const ref=$('#reference-'+r);if(ref){ref.closest('details').open=true;setTimeout(()=>ref.scrollIntoView({behavior:'smooth',block:'center'}),80)}});span.append(a)});span.append(']');frag.append(span)}else frag.append(document.createTextNode(piece))});node.replaceWith(frag)});
}
function wrapTables(){$$('#readerChapters table, #glossaryContent table').forEach(t=>{const w=text('div','','table-scroller');t.replaceWith(w);w.append(t)})}
// Routing & events
 document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){e.preventDefault();view(go.dataset.go,go.dataset.chapter);return;}const bookmark=e.target.closest('[data-bookmark]');if(bookmark){markBookmark(bookmark.dataset.bookmark);return;}const image=e.target.closest('[data-image]');if(image){openImage(image.dataset.image);return;}const action=e.target.closest('[data-action]');if(action){activateSource(action.dataset.action);return;}});
$('#savedShortcut').addEventListener('click',()=>view('saved'));
$('#searchTrigger').addEventListener('click',()=>openSearch());$('#searchTrigger').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openSearch()}});
$('#searchClose').addEventListener('click',closeSearch);$('#searchOverlay').addEventListener('click',e=>{if(e.target.id==='searchOverlay')closeSearch()});$('#searchInput').addEventListener('input',renderSearch);
$('#lightboxClose').addEventListener('click',closeImage);$('#lightbox').addEventListener('click',e=>{if(e.target.id==='lightbox')closeImage()});$('#stageThumb').addEventListener('click',()=>openImage('figure1'));$('#stageThumb').addEventListener('keydown',e=>{if(e.key==='Enter')openImage('figure1')});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeImage();closeSearch()}if(e.key==='/'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){e.preventDefault();openSearch()}});
 $$('#animalFilters .filter').forEach(b=>b.addEventListener('click',()=>{caseFilter=b.dataset.animal;$$('#animalFilters .filter').forEach(a=>a.classList.toggle('active',a===b));renderCases()}));
$('#expandAll').addEventListener('click',()=>$$('#readerChapters .chapter').forEach(d=>d.open=true));$('#collapseAll').addEventListener('click',()=>$$('#readerChapters .chapter').forEach(d=>d.open=false));
window.addEventListener('scroll',updateProgress,{passive:true});window.addEventListener('resize',updateProgress);window.addEventListener('hashchange',()=>{const val=location.hash.slice(1);if(val&&val!==currentView)view(val)});
renderStages();renderHistology();renderEndos();renderCases();syncBookmarks();linkCitations();wrapTables();view(location.hash.slice(1)||'overview');
})();
